[mypy]
python_version = 3.12
strict = True
exclude = (?x)(
    ^generated/
    )

[mypy-BatchLexer.*]
ignore_missing_imports = True

[mypy-BatchParser.*]
ignore_missing_imports = True

[mypy-BatchParserVisitor.*]
ignore_missing_imports = True
[mypy-jsonschema.*]
ignore_missing_imports = True

[mypy-antlr4.*]
ignore_missing_imports = True

